"""Build on the destination OS; Python and websockets are included by PyInstaller."""
import argparse
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from remoteinput.config import relay_url  # noqa: E402


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--relay-url", default=os.environ.get("REMOTEINPUT_RELAY_URL", ""))
    parser.add_argument("--unconfigured", action="store_true", help="Create an explicitly setup-pending validation build.")
    args = parser.parse_args()
    if args.relay_url:
        url = relay_url(args.relay_url)
    elif args.unconfigured:
        url = ""
    else:
        parser.error("Set --relay-url to the deployed wss://host/ws. Use --unconfigured only for validation builds.")
    config = ROOT / "src/remoteinput/_deployment.py"
    previous = config.read_bytes() if config.exists() else None
    try:
        config.write_text("# Generated by scripts/build.py; contains no secrets.\nRELAY_URL = " + repr(url) + "\n")
        command = [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", "--console", "--onedir",
                   "--name", "RemoteInput", "--paths", str(ROOT / "src"),
                   "--collect-submodules", "websockets", "--hidden-import", "remoteinput._deployment"]
        if sys.platform == "darwin" and os.environ.get("MACOS_SIGN_IDENTITY"):
            command += ["--codesign-identity", os.environ["MACOS_SIGN_IDENTITY"]]
        command.append(str(ROOT / "scripts/entry.py"))
        subprocess.run(command, cwd=ROOT, check=True)
        folder = ROOT / "dist/RemoteInput"
        extension = ".exe" if sys.platform == "win32" else ""
        binary = folder / ("RemoteInput" + extension)
        subprocess.run([str(binary), "self-check"], check=True)
        launchers = {"Start Target": "target", "Start Controller": "controller", "Forget Target": "forget-target",
                     "Measure Relay": "probe"}
        for title, mode in launchers.items():
            if sys.platform == "win32":
                (folder / (title + ".cmd")).write_text('@echo off\r\n"%~dp0RemoteInput.exe" ' + mode + '\r\npause\r\n')
            else:
                path = folder / (title + ".command")
                path.write_text('#!/bin/sh\ncd -- "$(dirname -- "$0")" || exit 1\n./RemoteInput ' + mode +
                                '\nprintf "\\nPress Enter to close."\nread -r answer\n')
                path.chmod(0o755)
        shutil.copy(ROOT / "docs/SETUP.md", folder / "READ-ME-FIRST.md")
        shutil.copy(ROOT / "docs/TESTING.md", folder / "TESTING.md")
        (folder / "BUILD-INFO.json").write_text(json.dumps({"os": sys.platform, "architecture": platform.machine(),
            "relay_url": url, "ready_for_pairing": bool(url), "signed": bool(os.environ.get("MACOS_SIGN_IDENTITY")),
            "note": "Native interactive behavior requires the manual checks in TESTING.md."}, indent=2) + "\n")
        if not url:
            (folder / "SETUP-PENDING.txt").write_text("This build has no hosted relay address. The developer must deploy "
                "the relay and rebuild with --relay-url before distributing a ready-to-run app.\n")
        label = f"RemoteInput-{platform.system()}-{platform.machine()}" + ("" if url else "-setup-pending")
        if sys.platform == "win32":
            archive = Path(shutil.make_archive(str(ROOT / "dist" / label), "zip", root_dir=folder))
        else:
            archive = ROOT / "dist" / (label + ".tar.gz")
            with tarfile.open(archive, "w:gz") as tar:
                tar.add(folder, arcname="RemoteInput")
        (ROOT / "dist" / (archive.name + ".sha256")).write_text(hashlib.sha256(archive.read_bytes()).hexdigest() +
                                                               "  " + archive.name + "\n")
        print(f"Package: {archive}")
    finally:
        if previous is None:
            config.unlink(missing_ok=True)
        else:
            config.write_bytes(previous)


if __name__ == "__main__":
    main()

